{% set version = "2.4-4" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-bio3d
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/bio3d_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/bio3d/bio3d_{{ version }}.tar.gz
  sha256: 5654eac10d33e4235ef89292e3b99006d8812b6bfaaa3d6fb540312160fd9de9

build:
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-rcpp
  run:
    - r-base
    - r-rcpp

test:
  commands:
    - $R -e "library('bio3d')"           # [not win]
    - "\"%R%\" -e \"library('bio3d')\""  # [win]

about:
  home: http://thegrantlab.org/bio3d/, http://bitbucket.org/Grantlab/bio3d
  license: GPL-2.0-or-later
  summary: Utilities to process, organize and explore protein structure, sequence and dynamics data. Features include the ability to read and write structure, sequence and dynamic trajectory data, perform sequence and structure database searches, data summaries, atom selection, alignment, superposition, rigid core identification,
    clustering, torsion analysis, distance matrix analysis, structure and sequence conservation analysis, normal mode analysis, principal component analysis of heterogeneous structure data, and correlation network analysis from normal mode and molecular dynamics data. In addition, various utility functions are provided to
    enable the statistical and graphical power of the R environment to work with biological sequence and structural data. Please refer to the URLs below for more information.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr

# Package: bio3d
# Title: Biological Structure Analysis
# Version: 2.4-0
# Authors@R: c(person("Barry", "Grant", role=c("aut", "cre"), email="bjgrant@ucsd.edu"), person("Xin-Qiu", "Yao", role="aut"), person("Lars", "Skjaerven", role="aut"), person("Julien", "Ide", role="aut"))
# Author: Barry Grant [aut, cre], Xin-Qiu Yao [aut], Lars Skjaerven [aut], Julien Ide [aut]
# VignetteBuilder: knitr
# LinkingTo: Rcpp
# Imports: Rcpp, parallel, grid, graphics, grDevices, stats, utils
# Suggests: XML, RCurl, lattice, ncdf4, igraph, bigmemory, knitr, testthat (>= 0.9.1), httr, msa, Biostrings
# Depends: R (>= 3.1.0)
# LazyData: yes
# Description: Utilities to process, organize and explore protein structure, sequence and dynamics data. Features include the ability to read and write structure, sequence and dynamic trajectory data, perform sequence and structure database searches, data summaries, atom selection, alignment, superposition, rigid core identification, clustering, torsion analysis, distance matrix analysis, structure and sequence conservation analysis, normal mode analysis, principal component analysis of heterogeneous structure data, and correlation network analysis from normal mode and molecular dynamics data. In addition, various utility functions are provided to enable the statistical and graphical power of the R environment to work with biological sequence and structural data. Please refer to the URLs below for more information.
# Maintainer: Barry Grant <bjgrant@ucsd.edu>
# License: GPL (>= 2)
# URL: http://thegrantlab.org/bio3d/, http://bitbucket.org/Grantlab/bio3d
# RoxygenNote: 5.0.1
# NeedsCompilation: yes
# Packaged: 2019-11-25 20:41:16 UTC; xinqyao
# Repository: CRAN
# Date/Publication: 2019-11-26 17:40:05 UTC
