{% set version = '2.3-3' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-bio3d
  version: {{ version|replace("-", "_") }}

source:
  fn: bio3d_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/bio3d_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/bio3d/bio3d_{{ version }}.tar.gz

  sha256: f4b45847eb8a4175dacea659f30a8075769ec1ae19daec6842b0d72227b48633

build:
  merge_build_host: True  # [win]
  number: 1
  skip: true  # [win32]

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - posix                # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ compiler('cxx') }}        # [unix]
    - {{ compiler('m2w64_cxx') }}  # [win]
  host:
    - r-base
    - r-rcpp

  run:
    - r-base
    - r-rcpp

test:
  commands:
    - $R -e "library('bio3d')"  # [not win]
    - "\"%R%\" -e \"library('bio3d')\""  # [win]

about:
  home: http://bitbucket.org/Grantlab/bio3d
  license: GPL (>= 2)
  summary: Utilities to process, organize and explore protein structure, sequence and dynamics
    data. Features include the ability to read and write structure, sequence and dynamic
    trajectory data, perform sequence and structure database searches, data summaries,
    atom selection, alignment, superposition, rigid core identification, clustering,
    torsion analysis, distance matrix analysis, structure and sequence conservation
    analysis, normal mode analysis, principal component analysis of heterogeneous structure
    data, and correlation network analysis from normal mode and molecular dynamics data.
    In addition, various utility functions are provided to enable the statistical and
    graphical power of the R environment to work with biological sequence and structural
    data. Please refer to the URLs below for more information.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}\/lib\/R\/share\/licenses\/GPL-3'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-3'  # [win]
extra:
   recipe-maintainers:
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
