travis:
  secure:
    BINSTAR_TOKEN: WafEDGo1KsD0uyQdi/fYrWex1CH/c1mBhVt+l0zE2Wn0iMqYJyts4hshSbpvDEnlIOVieSGui4VANthYHoD9lvDTOFQFAP6zGUfRmXTIZkmsXmV017QhbOy7AWBNwzdIMINXfvkRUXPuhNEpRc1qYmHY/ukM4VI2WE8yYl7kOLFvqrc/eDwEq5SO2NA/Hdivfb+KcbJSiefnmtWgngt5imhl5aXcKirx5pNR+ux8b9pC/H734t326q4xJRkaIJphpjWlTCYcJdv+wXGjlMxhg6ccGCuUh1zrvO/C6/oUjxMr7LJOxHa9/XRLAPShbWG1Lso197G2EfPpFNf+M1n4mlW0nA+3zl78jGoMMgQ8FRVnk9lYUUDfR1OFS2mpiO9ySXTTReTasEb7rU6nIMR/78JEySUi7hyTRfeD1Wsvdsz06g9MBXhabLlMTS4mgd2flOF4jgF3zNFETpN+gLjBPpnH1yZPTcRc8H/hwYUfnOxsOejGFA/h6/O+tCbIaqYuWgDxz/J+kh6QxOGL5Djceevu3czoi+evv/7fqc0KvoRvxmpznGB7JALxMD/ZoXkvo5cnmRN8es9kVHEheZieTToohx1SXfxLspc4quTh5NDvMzA2fkdTNfANLXLKFXtge5VNQQl/GCxLlrCrSDiZOLvfnUhIfT4TbEMaupOxU5A=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
