travis:
  secure:
    BINSTAR_TOKEN: ocJrlrAC/3RJQ4U0z0Dn5W3wrXgHU3XYvkP9uRGtucm8ayW0m+MOSdxVCuYYa5I3hhu5gP7vY5BinNEgiF0z4R4rqRAMsfgY3rYeUUcFinWxM+cd1Q3nPKglMp7TuOOc7W/XIJQ9CgX7zuL+QL9e4WocR/MsgVB0dhbCnnuo10b0QeLxdmiL5dMWodClf3ww/eDgUAWbs+78NDzAHwPjwF9tPrFIB4Ag6NFXD3YcT2hfgxr76BlvD1z0zzIFc40KlgGqNj2mh3sQs/3U1PwIjnFqGHbYQY9N3LVDyR++SYq2c8JmJVE86RsLs3KkBoWu7uLAxBS2RbqnRRGWCq7pfyb7rOGpG+E2OrO6BNg+QmP4dKYkTquXUC+R0slqKx9v/zLDvgL+jUoctTXdhOiiL/fgMRWIABl/ZytdIlMvFwOOQ1EAa6eY0Sbp9xSa6WrsLnWxujp0H6jtnKvN5R9FoB2dDM9Hh11S3B+a1Kph0ee7AJRYRTm/9xIT66GcNMXdhfb6XC00EEvSQUcq1suhdhE/8h2IMzzxiWFqyUQVmmPUXrKCqAUCs0xIxbj+RbaK0kmAK86A6n+6qTgEDerliEw8aOX2F1cl429Kedj8aNR+WFZ6B68QJvR2OENP4zjCV3jYTilEl7VhUqmVK9T8qDuhRP7mn7TGAHcbS7yciMs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
