travis:
  secure:
    BINSTAR_TOKEN: RfJZa4wJFPC7+CI5Jo4g8dM5eFWLbCccEmTtau9V5h8aSFrTSZD2fYvoV7TUrhxsCuE50Hli6SKxAIioVObDsTwy8oRSapb0XwdtypjXj96/Qqv1FHsSpHe/YOiYbrquuGyra42HxHQwKTNEXBBNFjpjOxHbpl81xoF+EeadhZxAClWjb+7mnYAypWNOzrjaz/eVGwtk+SR5Q0+cjt51hhXgBcI8n3CyIVPE6TEUTCoxuKaFv2LHwqfOVC5R+o7piYHXoyC34CBcQG6qVcEYnZTpVFBJb9R/dVhhJ2UGhViArGdF0iMisfd6EV4G0wotzwQ01pCOymHOtDRsB2/whAdYn+UtvpYhG+aDIItZh+kgA7qRSIqMrLZHAgcyYD0MGyZsRBBzoh04XOwQqwudrKbJs9tP8T/ZsBuaJa5m8RY8AvKH/vZWgr0mviTk0rRcItGXf5IVrniB+WMcdzLjeHxuWroNpmHP2jY4sII4lGuo8Mn6oKnr8uT+I0dumd53MawAWR5adPa/SGYe5T40AQw70P3yxACtKZP2ouq7Gsp65o5ZTN25DtZtJOWjRsVhmQ+L7yzTtILHNFi9N8UWsm+jIuo8z8aHOw1MDVkrHOxPXdK7Mvz3HmHTgmNL4I83bFqML1v18J13hjo98nyBFA/pLTQ9pgllNqkfsnOsz+E=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
