travis:
  secure:
    BINSTAR_TOKEN: jO62Eqwy5fCj+DX90LjK2XAEhJ+HJDFLvstGGg6PFqAaeMD0azH0J0K7Z1jzbJTek8ZtTqAqqejUaJsFGo07kvEzCxJjiKcnMBlkxtbZiISyaJbcC86+Y7M7aSCi8T+7bSBa2pA35fyqsQ0CWH07wxhmEiWMHQT3e/eKO6pYgThbdbd29EnM27LGkJxVUVrijmNYhGeF525RoLJQlHAkY35maz6LDxNfVOxLda+mmywR9fmQ2HiQbSzqeZrXSUEhx9WEfrI2xNILO4U4vTKWzu7zACzFVWqGU4mCLyvffx2c9xaca93ngWXvLCBMOtCognot2NTxXHPfhzhiD7RQt1X0qdmyMmKxinY6ZtZTFpcC6Rxhz96R4PNleNJzTLpK5TYmMrWkbX402rEBR2OWRA5r1mXVYKZ6jHUQYHHGoFhr68b0HT+bgpmEFJasbSUteOcpzDGOMZ4SvTWsIU6YcrocDtlctsgJJ2tAd1rGDkXUPfOMYKZixQ7lCpP/4m2mzS8jW4jwb2J/eE7na2pS0EDoLA++EqsBMZ2stsyoDYb5W+QQOJmXSnGYVfouY3aDzHM0AC1t384uuFiabMpmTj0wDuaHDOezHfXBBl9anp+yBX4irLXs8sYo8ykTDk+hy9UiNkN9qfM2VFQO1KAzrVOgeXEoRjrqrBcDFubMN9I=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
