travis:
  secure:
    BINSTAR_TOKEN: pq0FS6JdZal7AHRkX0W88s/cJZXlLXVpftAm89c9ou0k7vgtbR0JVjsUdumnNlZz87ikteM2ZG+30x28A3uAP0qEiFtDtIQaq9nHB7X9ZS/7G/iG8DfluPb5ilmpjyN+jFblX/MDVI99/eGGWd0qKX68GO6ozvnIdNunPK8pHdXKsqwHRho4HZ1Os0FuC/+Zjdtd6tqNBUqYA5rRjYOkjjdXuJ0JfN7YlCqu0Kx9GgE1wKcoDSRXh535lGl6sxStkM2+tEozzGYF5qv1kDlSxeF5dotOrtfJ+SLr3Xjy/fZWRSajQjDf1acB9zkUZM3kMhjs7nlxn6fQJ63B4kJNq+DZNdFgjzw+PvalRrRBPaY2hoET2wlxgqx5c6teoJNuaLDOXTMHSyxzEC9vXqHRuRGwHyyBOIZyFJ8ImVSK2TeLk6A6XaUhUvIr8u+YqpbEROECziNtqUbpwUCbiOLBLwt1lnkcTV0MiitJnLLGE1/s/fkRwc7H909lgMiq67ZeudLv8uU7Z2e31IjVMXDR+28B++kB6lkMoHlAqtKjhuG4iBiH6zrmyXZM2GlXP6/Jb1dAM5Ellf0IP6DnJYSIDZPn0KA2FJm4aFYlPu7khJE3olV+4qi7U+GbpB0k7kbJNeC2Q6Tc04bbVq1pvZRwHJcOH6nKF8NNTmU7bCUVtx8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
